//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSession
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamSessionEntities : DbContext
    {
        private static ExamSessionEntities _context;

        public ExamSessionEntities()
            : base("name=ExamSessionEntities")
        {
        }
        public static ExamSessionEntities GetContext()
        {
            if (_context == null)
                _context = new ExamSessionEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<РазработкаИС> РазработкаИС { get; set; }
        public virtual DbSet<ТестированиеИС> ТестированиеИС { get; set; }
    }
}
