//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSession
{
    using System;
    using System.Collections.Generic;
    
    public partial class РазработкаИС
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Номер_билета { get; set; }
        public Nullable<int> Оценка { get; set; }
    }
}
